### PR TITLE
[production] Add docker build and push CI workflow

### PR DESCRIPTION
**Pull request by dcroote**
Same as #359 (including image name & tag feedback updates) but for the `production` branch

### CODE REVIEW

**Review by mcoetzee — APPROVED** [review]
👍 What's the plan with the `DOCKERHUB_USERNAME` and `DOCKERHUB_TOKEN` secrets? I am able add them if needed.

**Comment by dcroote** [comment]
Thanks for the offer @mcoetzee, though I'm not sure I understand you correctly- do you have access to the api3 dockerhub account to generate the token that needs to be saved?

@aquarat perhaps you are the one to ask to assist here? We need two secrets added: `DOCKERHUB_USERNAME` is simply `api3`, while `DOCKERHUB_TOKEN` needs to be generated in docker hub and added.

**Comment by mcoetzee** [comment]
> do you have access to the api3 dockerhub account to generate the token that needs to be saved?

Sorry no I don't, but I do have the ability to add secrets to this repo 👍

**Comment by dcroote** [comment]
> Sorry no I don't, but I do have the ability to add secrets to this repo 👍

Thanks @mcoetzee - could you then add `api3` as the value for `DOCKERHUB_USERNAME`? This should fix the `main` builds at least.

@aquarat - it looks like we'll still need you for generating a Docker Hub token and adding it as the secret `DOCKERHUB_TOKEN` when you get the chance.

**Comment by mcoetzee** [comment]
> Thanks @mcoetzee - could you then add `api3` as the value for `DOCKERHUB_USERNAME`?

Done 👍. The `main` build is passing again ✅

**Comment by aquarat** [comment]
> @aquarat - it looks like we'll still need you for generating a Docker Hub token and adding it as the secret `DOCKERHUB_TOKEN` when you get the chance.

Apologies, I'll add this in a moment 👌

**Comment by aquarat** [comment]
Sorry I missed this, if I miss something again feel free to message me on Slack. 
Do you still need this secret added?

**Comment by mcoetzee** [comment]
> Do you still need this secret added?

Yes please @aquarat

**Comment by aquarat** [comment]
I've updated `DOCKERHUB_USERNAME` and `DOCKERHUB_TOKEN`, give it a go 🚀 . Sorry it took so long.

**Comment by dcroote** [comment]
Thanks @aquarat, but it looks like you used `api3ci` rather than `api3` as the `DOCKERHUB_USERNAME` (given that's where I [found the pushed image on docker hub](https://hub.docker.com/r/api3ci/dao-dashboard/tags)). Is there a reason to not have this image pushed to where all of the other API3 images are (under the `api3` username)?

**Comment by aquarat** [comment]
Hey @dcroote 
We generally push images to the main image repositories manually because an automated process is (generally considered to be) easier to compromise and in this case, if the main Action was compromised it would allow someone to upload a malicious image. An example malicious image could be a bad deployer that steals Airnode funds 🤷

**Comment by dcroote** [comment]
Thanks @aquarat! Appreciate the security considerations. Indeed this is only triggered on a push to `main` or `production` so it running is controlled by those with write access.

**Pull request merged**
